CREATE TABLE IF NOT EXISTS "default_clocks" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"name" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS "tasks" (
	"id" INTEGER PRIMARY KEY AUTOINCREMENT,
	"description" TEXT NOT NULL,
	"is_completed" BOOLEAN DEFAULT 0,
	"created_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"updated_at" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"deleted_at" DATETIME
);

CREATE TRIGGER IF NOT EXISTS update_tasks_timestamp 
AFTER UPDATE ON tasks
FOR EACH ROW
BEGIN
    UPDATE tasks SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;

